# .github/workflows/ci-cd.yml
name: vanilajs-frontend CI/CD

on:
  push:
    branches:
      - main
      - action
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      #- name: Run tests
      #  run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - name: Check Server Status
        id: check_status
        run: |
          if [ "${{ secrets.SERVER_STATUS }}" == "true" ]; then
            echo "::set-output name=status::true"
          else
            echo "::set-output name=status::false"
          fi

      - name: Checkout repository
        if: steps.check_status.outputs.status == 'true'
        uses: actions/checkout@v2

      - name: Set up Node.js
        if: steps.check_status.outputs.status == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # 나머지 스텝들도 동일한 if 조건을 추가합니다.
      - name: Install dependencies
        if: steps.check_status.outputs.status == 'true'
        run: npm install

      - name: Prepare SSH Key
        if: steps.check_status.outputs.status == 'true'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        if: steps.check_status.outputs.status == 'true'
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          nvm use 20
          cd /home/${{ secrets.SERVER_USER }}/frontend
          git checkout -b main
          sudo git pull origin main
          sudo chown -R $USER /home/ubuntu/frontend
          sudo chmod -R 777 /home/ubuntu/frontend
          npm install
          pm2 kill
          pm2 start app.js --name "github-action-app"
          EOF